### ISSUE TITLE
how to do downstream task for 4 patches jigsaw 

### ISSUE THREAD

**Issue by ramdhan1989** [virtualgraham/sc_patch#1]
Hi, this is good application. how to do downstream task using label dataset for image classification after we trained the pretext model ? thank you

**Comment by virtualgraham** [comment]
This is not really a library. Its more just a set of experiments. However, after you train the model what you can do is put it into evaluation mode. The output will be a patch descriptor or representation, which can be used for a bunch of things. For example you can use k-means clustering.

**Comment by ramdhan1989** [comment]
I am trying to understand the data flow in jigsaw puzzle (4 patches) during the pretext task. In this repo you use 96×96 image size for each patch that passed to certain backbone (ex: alexnet) with shared weights (a model with shared weights mean same model isn't it ?). For production purpose, Do I need to cut the whole image into pieces/patches (size 96×96) and passed again to 4 backbones, concatenate, and connect to FC layers and new classifier (to learn mapping with actual label class)? or I just need to use one backbone and pass to it the whole image directly (need to resize whole image into 96×96 ? or can use any size of 32 multiplication? ), connect to FC layers and new classifiers ?
I see in your patch_clustering_copy.ipynb seems only pass one patch from an image resulting a representation of the patch. I think for image classification we need representation that describe whole image information.
Any advise or suggestions ?
thank you

**Comment by virtualgraham** [comment]
Your question of how to use the patch representations for image classification is a good one. In the paper Revisiting Self-Supervised Visual Representation Learning :

> we extract representations by averaging the representations of nine uniformly sampled, colorful, and normalized patches of an image.

This is why patch based methods are typically less desirable for the image classification the transfer learning tasks. The Image rotation pretext and contrastive methods are used instead.

However the goal of my experiments was to use the patch descriptors as object part representations for object detection. I tried a bunch of object part methods such as the Constellation Model. But I was unable to identify objects better than using whole image descriptors.

**Comment by ramdhan1989** [comment]
understand, thanks a lot
